### ISSUE TITLE
Move randomcoloR to Suggests

### ISSUE THREAD

**Issue by ashiklom** [jbferet/prospect#5]
`randomcoloR` depends on `V8`, which requires a system library (V8 engine). That's a significant dependency just to get more pleasing colors in one visualization in the package.

I suggest the following:

(1) Move `randomcoloR` to `Suggests`.

(2) Remove the `importFrom randomcoloR distinctColorPalette` from `R/Lib_PROSPECT_Inversion.R`.

(3) Replace the relevant part of the `plotinv` code with something like this:

```r
  if (is.null(Colors)) {
    if (requireNamespace("randomcoloR")) {
      # If `randomcoloR` is installed, use it.
      Colors <- randomcoloR::distinctColorPalette(unique(BP_df$config))
    } else {
    # If not, fall back on the built-in (but less pleasing) rainbow color palette (or some other default palette)
      Colors <- rainbow(unique(BP_df$config))
    }
  }
```

This will make the package much easier to install!

---

More generally, it's a good idea to only _require_ dependencies that are essential to the core functioning of the package (in this case, things like `expint` and the libraries used for the inversion) and _suggest_ stuff that is useful for _demonstrating_ capabilities of the package (e.g., `ggplot` for inversion plotting; `data.table` for loading example data).

**Comment by earth-chris** [comment]
I'd like to second this recommendation. I spent a good chunk of time figuring out how to install V8 (and found [this set of solutions](https://stackoverflow.com/questions/62302713/not-able-to-install-v8-package-on-ubuntu)). If you plan to keep this is a required dependency, I might recommend providing links or tips on how to install this dependency.

**Comment by jbferet** [comment]
sorry for the waste of time @earth-chris ! and thank you @ashiklom for noticing this issue. This function is actually not strictly needed, and I could not find any direct use in the current version of the package. 
so I will remove it from the next release. It will make it easier, and reduce dependency to other packages.

**Comment by jbferet** [comment]
I decided to get rid of the function plotinv in prospect v1.5.0.  randomcoloR is now unnecessary.
Sorry again for the difficulties you had to install v8, @earth-chris. I guess you were not the only one, but the issue was not raised. 
I may add support for plots in a next version, but will be more careful with the packages involved.
